### PR TITLE
Streaming

### PR DESCRIPTION
**Pull request by Deraen**
Continued from #53 

I've added create-parser function for accessing low-level parser & extended ReadValues for parser.

This allows finding array inside Json objects etc. and then reading and array of values from that.

Probably there could be similar functions for writer.

### CODE REVIEW

**Comment by bsless** [comment]
Hi @Deraen, any update on this?

**Comment by Deraen** [comment]
Trying to find my notes about this... hmm.

I think I was a bit unhappy `-read-values` implementation for `JsonParser`, as it needs to move the parser token to a specific point etc. The `create-parser` part from my change is fine, but I wonder if it would be better to leave `readValuesAs` part for the lib users. Or maybe it would be better as a separate function, instead of making `read-values` work in every case.

The parser object already has reference to Jsonista ObjectMapper, so calling `readValuesAs` directly is simpler than with `InputStream` and other, where `.readerFor` call is first needed...

**Comment by bsless** [comment]
Hi @Deraen, been a while since we've both looked at it :)
Coming back to the subject, I am not sure I see the rationale in working via a parser.
Would the user API be different? Will there be a difference in performance? What's the differences in the code paths?
Via parser:
- mapper -> factory -> parser -> read values as T -> iterable
Via reader:
- mapper -> reader for T -> read values -> iterable
Unless you want to expose the type for the parser as an argument.
Not sure if I missed something

**Comment by Deraen** [comment]
@bsless The last test cases shows the use case for the parser.

To read and array lazily from a JSON stream, which is not an top level array, user needs to use parser to navigate to specific element and then the array can be read.

In #53 we already discussed difference to `readTree` version I've used with GeoJSON files.

I think the API we'll provide should cover both cases: top level arrays, reading large GeoJSON file feature arrays, and also read log files without top level array start, separator and end elements. Though I think the last case is already covered by reading the file using Reader, readLine and then parsing each line with `read-value`.

**Comment by viesti** [comment]
> read log files without top level array start, separator and end elements. Though I think the last case is already covered by reading the file using Reader, readLine and then parsing each line with read-value.

Piping in that this last one is common enough that it's called [ndjson](http://ndjson.org/) :)

**Comment by bsless** [comment]
Thank you for helping me get back into context :)
Now I see the justification for the parser, and then obviously read-values could be implemented with it to avoid duplication. If it ends up hitting the same code paths I see no inherent problem.
We should add tests, but I think reading newline delimited json could even be done without using a reader/readLine, which I would actually prefer because why create intermediary strings? read-values should be able to handle it directly as a stream.
Would you like me to PR this changes against this branch?

**Comment by Deraen** [comment]
@bsless If you have idea how to clean up the implementation, go ahead.

Maybe the problem I had was that parser `.readValuesAs` doesn't handle that array start element? The parser needs to be on the correct position when calling that.

I wonder if there is something on Jackson API to handle these cases better.

>  I think reading newline delimited json could even be done without using a reader/readLine, which I would actually prefer because why create intermediary strings?

Makes sense.

**Comment by bsless** [comment]
Digging through Jackson's API, it should be possible to get the parser from the `MappingIterator` returned from `readValues`, letting us drop that piece of code. wdyt?

**Comment by Deraen** [comment]
Boilerplate on the library code isn't a problem. Macros can make namespace load times much worse and make it harder to understand the code.

**Comment by bsless** [comment]
Alright, where does it leave us with regards to everything else? What do you think about the relation between `readValues` and the parser? It seems to me like the should remain separate. `readValues` deals explicitly with streams while the parser's main benefit is in navigating a data structure.

**Comment by opqdonut** [comment]
I think this can be closed since #82 is merged

**Pull request closed without merging**
